spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/socialNetwork
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

